global:
  name: &name base_b2
  fold: &fold 4
  version: &version f4

model:
  type: SMPModel
  model_type: Unet
  model_name: timm-efficientnet-b2
  pretrained_weight: noisy-student
  num_classes: 1

loss: [
  {type: BCEWithIgnoreLoss, loss_name: bce_loss, ignore_index: 255, loss_weight: 1.0},
  {type: DiceLoss, loss_name: dice_loss, loss_weight: 1.0},
]

metric: 
  type: DiceMetric
  per_image: False

data:
  type: CropData
  fold: *fold
  num_folds: 5
  batch_size: 32
  stratified_by: null
  group_by: null
  dataset:
    image_size: 512
    trans: {
      train: [
        {type: HorizontalFlip, p: 0.5},
        {type: VerticalFlip, p: 0.5},
        {type: RandomRotate90, p: 0.5},
        {type: ShiftScaleRotate, rotate_limit: 15, border_mode: 0, value: 0, mask_value: 0, p: 0.5},
        {type: OneOf, transforms: [
          {type: ElasticTransform, p: 0.5},
          {type: GridDistortion, p: 0.5},
          {type: OpticalDistortion, p: 0.5},
        ], p: 1.0},
        {type: OneOf, transforms: [
          {type: ColorJitter, p: 0.5},
          {type: HueSaturationValue, p: 0.5},
          {type: RandomBrightnessContrast, p: 0.5},
        ], p: 1.0},
        {type: Normalize},
        {type: ToTensorV2},
      ],
      val: [
        {type: Normalize},
        {type: ToTensorV2},
      ]
    }

train:
  # optimizer
  optimizer: adam
  learning_rate: 1e-3
  weight_decay: 2e-5

  # scheduler
  num_epochs: 30
  scheduler: one_cycle

  # trainer
  monitor: val_dice
  log_step: 50
  val_interval: 1
  swa: False
  grad_clip: 0

name: *name
version: *version

